### ISSUE TITLE
SQL syntax Error

### ISSUE THREAD

**Issue by junli0411** [openark/orchestrator#965]
Hi, 
I got the following error in orchestrator.log 
2019-08-21 08:22:33 ERROR Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and cluster_name='xxxxxx:3306'' at line 6

the function ReplaceClusterName in file instance_dao.go , there's a sql error :
		_, err := db.ExecOrchestrator(\`
			update
				database_instance
			set
				cluster_name=?
			where
				**and** cluster_name=?
				\`, newClusterName, oldClusterName,
		)

**Comment by shlomi-noach** [comment]
This was fixed in latest release.

**Comment by shlomi-noach** [comment]
Or... actually I haven’t released since the fix has been merged! So it’s fixed in master branch. Release to follow.

**Comment by junli0411** [comment]
I'm not sure why , but I still get the same error sql in the master branch.

**Comment by shlomi-noach** [comment]
Please check https://github.com/github/orchestrator/releases/tag/v3.1.2

**Comment by junli0411** [comment]
double checked the v3.1.2 , it's still there.  ^_^
```
func ReplaceClusterName(oldClusterName string, newClusterName string) error {
	if oldClusterName == "" {
		return log.Errorf("replaceClusterName: skipping empty oldClusterName")
	}
	if newClusterName == "" {
		return log.Errorf("replaceClusterName: skipping empty newClusterName")
	}
	writeFunc := func() error {
		_, err := db.ExecOrchestrator(\`
			update
				database_instance
			set
				cluster_name=?
			where
				**and** cluster_name=?
				\`, newClusterName, oldClusterName,
		)
		if err != nil {
			return log.Errore(err)
		}
		AuditOperation("replace-cluster-name", nil, fmt.Sprintf("replaxced %s with %s", oldClusterName, newClusterName))
		return nil
	}
	return ExecDBWriteFunc(writeFunc)
} 
```

**Comment by junli0411** [comment]
Maybe it missed some columns before the 'and' or we need to remove the 'and'.

**Comment by shlomi-noach** [comment]
@junli0411 -- oh, the code is still there -- but no one is using it. Do you still see the error in your log?

BTW, pro tip: use markdown. Use three backtics to format your code. See how I've edited your previous comment.

**Comment by junli0411** [comment]
the log is only there when it's doing failover ,  I will check it when there's a failover next time. 
I will use markdown next time
